package FrontEndIdl;


/**
* FrontEndIdl/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/s_ursimr/git/DistributedSystemsProjectCOMP6231/ReplicaManager1FEandClient/src/FrontEnd.idl
* Monday, July 29, 2019 2:49:22 PM EDT
*/

public interface FrontEndOperations 
{
  String addEvent (String eventID, String eventType, String bookingCapacity, String managerID);
  String removeEvent (String eventID, String eventType, String managerID);
  String listEventAvailability (String eventType, String managerID);
  String bookEvent (String customerID, String eventID, String eventType, String bookingAmount);
  String getBookingSchedule (String customerID, String managerID);
  String cancelEvent (String customerID, String eventID, String eventType);
  String nonOriginCustomerBooking (String customerID, String eventID);
  String swapEvent (String customerID, String newEventID, String newEventType, String oldEventID, String oldEventType);
  String eventAvailable (String eventID, String eventType);
  String validateBooking (String customerID, String eventID, String eventType);
  void shutdown ();
} // interface FrontEndOperations
