package FrontEndIdl;


/**
* FrontEndIdl/FrontEndPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/s_ursimr/git/DistributedSystemsProjectCOMP6231/ReplicaManager1FEandClient/src/FrontEnd.idl
* Monday, July 29, 2019 2:49:22 PM EDT
*/

public abstract class FrontEndPOA extends org.omg.PortableServer.Servant
 implements FrontEndIdl.FrontEndOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addEvent", new java.lang.Integer (0));
    _methods.put ("removeEvent", new java.lang.Integer (1));
    _methods.put ("listEventAvailability", new java.lang.Integer (2));
    _methods.put ("bookEvent", new java.lang.Integer (3));
    _methods.put ("getBookingSchedule", new java.lang.Integer (4));
    _methods.put ("cancelEvent", new java.lang.Integer (5));
    _methods.put ("nonOriginCustomerBooking", new java.lang.Integer (6));
    _methods.put ("swapEvent", new java.lang.Integer (7));
    _methods.put ("eventAvailable", new java.lang.Integer (8));
    _methods.put ("validateBooking", new java.lang.Integer (9));
    _methods.put ("shutdown", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FrontEndIdl/FrontEnd/addEvent
       {
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String bookingCapacity = in.read_string ();
         String managerID = in.read_string ();
         String $result = null;
         $result = this.addEvent (eventID, eventType, bookingCapacity, managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // FrontEndIdl/FrontEnd/removeEvent
       {
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String managerID = in.read_string ();
         String $result = null;
         $result = this.removeEvent (eventID, eventType, managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // FrontEndIdl/FrontEnd/listEventAvailability
       {
         String eventType = in.read_string ();
         String managerID = in.read_string ();
         String $result = null;
         $result = this.listEventAvailability (eventType, managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // FrontEndIdl/FrontEnd/bookEvent
       {
         String customerID = in.read_string ();
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String bookingAmount = in.read_string ();
         String $result = null;
         $result = this.bookEvent (customerID, eventID, eventType, bookingAmount);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // FrontEndIdl/FrontEnd/getBookingSchedule
       {
         String customerID = in.read_string ();
         String managerID = in.read_string ();
         String $result = null;
         $result = this.getBookingSchedule (customerID, managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // FrontEndIdl/FrontEnd/cancelEvent
       {
         String customerID = in.read_string ();
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String $result = null;
         $result = this.cancelEvent (customerID, eventID, eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // FrontEndIdl/FrontEnd/nonOriginCustomerBooking
       {
         String customerID = in.read_string ();
         String eventID = in.read_string ();
         String $result = null;
         $result = this.nonOriginCustomerBooking (customerID, eventID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // FrontEndIdl/FrontEnd/swapEvent
       {
         String customerID = in.read_string ();
         String newEventID = in.read_string ();
         String newEventType = in.read_string ();
         String oldEventID = in.read_string ();
         String oldEventType = in.read_string ();
         String $result = null;
         $result = this.swapEvent (customerID, newEventID, newEventType, oldEventID, oldEventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // FrontEndIdl/FrontEnd/eventAvailable
       {
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String $result = null;
         $result = this.eventAvailable (eventID, eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // FrontEndIdl/FrontEnd/validateBooking
       {
         String customerID = in.read_string ();
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String $result = null;
         $result = this.validateBooking (customerID, eventID, eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // FrontEndIdl/FrontEnd/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FrontEndIdl/FrontEnd:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FrontEnd _this() 
  {
    return FrontEndHelper.narrow(
    super._this_object());
  }

  public FrontEnd _this(org.omg.CORBA.ORB orb) 
  {
    return FrontEndHelper.narrow(
    super._this_object(orb));
  }


} // class FrontEndPOA
