package FrontEndIdl;


/**
* FrontEndIdl/FrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/s_ursimr/git/DistributedSystemsProjectCOMP6231/ReplicaManager1FEandClient/src/FrontEnd.idl
* Monday, July 29, 2019 2:49:22 PM EDT
*/

public interface FrontEnd extends FrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEnd
